$primary = rgb(76946a)
$surface = rgb(1f1f28)
$secondary = rgb(c0a36e)
$error = rgb(c34043)
$tertiary = rgb(7e9cd8)
$surface_lowest = rgb(21212b)

plugin {
    hy3 {
        tabs {
            col.active = $secondary
            col.focused = $surface
            col.inactive = $surface_lowest
        }

        autotile {
            enable = true
        }
    }
}
